---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM user groups for administrators
Resources:
  AdminRoleToSwitch:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AdminRoleToSwitch
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 43200
      Tags:
        - Key: Name
          Value: AdminRoleToSwitch
  AdminRoleSwitcherGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: admin-role-switch-group
      Path: /
      Policies:
        - PolicyName: assume-admin-role-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !GetAtt AdminRoleToSwitch.Arn
  ReadOnlyUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: read-only-user-group
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
  SelfManagedIamUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: self-managed-iam-user-group
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/IAMSelfManageServiceSpecificCredentials
        - arn:aws:iam::aws:policy/IAMUserSSHKeys
      Policies:
        - PolicyName: iam-user-mfa-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateVirtualMFADevice
                  - iam:DeactivateMFADevice
                  - iam:DeleteVirtualMFADevice
                  - iam:EnableMFADevice
                  - iam:ListMFADeviceTags
                  - iam:ListMFADevices
                  - iam:ListVirtualMFADevices
                  - iam:ResyncMFADevice
                  - iam:TagMFADevice
                  - iam:UntagMFADevice
                Resource:
                  - 'arn:aws:iam::*:user/${aws:username}'
        - PolicyName: iam-user-access-key-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateAccessKey
                  - iam:DeleteAccessKey
                  - iam:GetAccessKeyLastUsed
                  - iam:ListAccessKeys
                  - iam:UpdateAccessKey
                Resource:
                  - 'arn:aws:iam::*:user/${aws:username}'
Outputs:
  AdminRoleToSwitchArn:
    Value: !GetAtt AdminRoleToSwitch.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AdminRoleToSwitchArn
  AdminRoleSwitcherGroup:
    Value: !Ref AdminRoleSwitcherGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AdminRoleSwitcherGroup
  ReadOnlyUserGroup:
    Value: !Ref ReadOnlyUserGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ReadOnlyUserGroup
  SelfManagedIamUserGroup:
    Value: !Ref SelfManagedIamUserGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SelfManagedIamUserGroup
