---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM user groups for administrators
Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub AdminRole-${AWS::AccountId}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: 43200
      Tags:
        - Key: Name
          Value: !Sub AdminRole-${AWS::AccountId}
  AdminRoleAssumerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub admin-role-assumer-group-${AWS::AccountId}
      Path: /
      Policies:
        - PolicyName: !Sub assume-admin-role-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !GetAtt AdminRole.Arn
  AccountRolesAssumerGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub account-roles-assumer-group-${AWS::AccountId}
      Path: /
      Policies:
        - PolicyName: !Sub account-roles-assumer-role-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/*
  ReadOnlyUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub read-only-user-group-${AWS::AccountId}
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
  SelfManagedIamUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Sub self-managed-iam-user-group-${AWS::AccountId}
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/IAMSelfManageServiceSpecificCredentials
        - arn:aws:iam::aws:policy/IAMUserSSHKeys
      Policies:
        - PolicyName: !Sub iam-user-mfa-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateVirtualMFADevice
                  - iam:DeactivateMFADevice
                  - iam:DeleteVirtualMFADevice
                  - iam:EnableMFADevice
                  - iam:ListMFADeviceTags
                  - iam:ListMFADevices
                  - iam:ListVirtualMFADevices
                  - iam:ResyncMFADevice
                  - iam:TagMFADevice
                  - iam:UntagMFADevice
                Resource:
                  - 'arn:aws:iam::*:user/${aws:username}'
        - PolicyName: !Sub iam-user-access-key-policy-${AWS::AccountId}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateAccessKey
                  - iam:DeleteAccessKey
                  - iam:GetAccessKeyLastUsed
                  - iam:ListAccessKeys
                  - iam:UpdateAccessKey
                Resource:
                  - 'arn:aws:iam::*:user/${aws:username}'
Outputs:
  AdminRoleArn:
    Value: !GetAtt AdminRole.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AdminRoleArn
  AdminRoleAssumerGroup:
    Value: !Ref AdminRoleAssumerGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AdminRoleAssumerGroup
  AccountRolesAssumerGroup:
    Value: !Ref AccountRolesAssumerGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AccountRolesAssumerGroup
  ReadOnlyUserGroup:
    Value: !Ref ReadOnlyUserGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-ReadOnlyUserGroup
  SelfManagedIamUserGroup:
    Value: !Ref SelfManagedIamUserGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-SelfManagedIamUserGroup
