---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM user group to switch roles
Resources:
  AccountRolesSwitcherGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: account-roles-switch-group
      Path: /
      Policies:
        - PolicyName: account-roles-switch-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - '*'
Outputs:
  AccountRolesSwitcherGroup:
    Value: !Ref AccountRolesSwitcherGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AccountRolesSwitcherGroup
